# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'ParkingPal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ParkingPal
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'SwipeCellKit'
    pod 'SVProgressHUD'
    pod 'ArcGIS-Runtime-SDK-iOS', '100.2.1'

  target 'ParkingPalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ParkingPalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
